### ISSUE TITLE
Inspect Element with debug on

### ISSUE THREAD

**Issue by paulmolluzzo** [sindresorhus/electron-context-menu#1]
If the app has `electron-debug` then there should be an item to "Inspect Element" like in Chrome that opens the inspector and highlights the appropriate element in the DOM.

**Comment by paulmolluzzo** [comment]
Maybe this can just be used as a dependency of `electron-context-menu`? You wouldn't want two context menus that could conflict. https://github.com/parro-it/debug-menu

**Comment by sindresorhus** [comment]
How about instead depend on https://github.com/sindresorhus/electron-is-dev and show the `Inspect Element` menu when it's in dev? No need for the user to use `electron-debug`. We could then just recommend this module in the `electron-debug` readme if they want `Inspect Element`.

**Comment by paulmolluzzo** [comment]
> How about instead depend on https://github.com/sindresorhus/electron-is-dev and show the Inspect Element menu when it's in dev? No need for the user to use electron-debug.

Yes I agree, that's a more direct solution.

**Comment by sindresorhus** [comment]
Alright. PR welcome :)

**Comment by parro-it** [comment]
> Maybe this can just be used as a dependency of electron-context-menu? You wouldn't want two context menus that could conflict. https://github.com/parro-it/debug-menu

I noticed these kind of conflicts within different context menu, so sometimes ago I wrote [electron-contextmenu-middleware](https://github.com/parro-it/electron-contextmenu-middleware) to solve the issue. It allow you to compose different context menus with a middleware style pattern.

[https://github.com/parro-it/electron-input-menu](electron-input-menu) is another module that use this pattern.

Maybe you could be give it a shot, it could be useful to integrate the idea in this repo?

**Comment by paulmolluzzo** [comment]
@parro-it thanks, I actually found your repos when I implemented my PR and learned some stuff from your code! :smile:

I didn't implement your middleware package b/c it would have required refactoring other parts (right?) and didn't know if @sindresorhus would have an opinion.

**Comment by sindresorhus** [comment]
I deliberately wanted something opinionated and simple for my apps. All that's required is [one line](https://github.com/sindresorhus/anatine/blob/8a091bbd62057b373904da606223882547f2b491/index.js#L13). Users can't change the core functionality here, but they can add stuff if they need to. Fits my needs better.

**Comment by parro-it** [comment]
> @parro-it thanks, I actually found your repos when I implemented my PR and learned some stuff from your code! :smile:

That's great to hear! I'm honestly feeling bad because I noticed this module when Sindre create it. I thought to get in touch but than completely forgot about it...

Anyway, If it's not too late I still think that the idea of using middleware pattern to integrate multiple context menu providers could deserve further discussion... I would be happy to help you and eventually integrate my context-menu related modules with `electron-context-menu` (or the other way around).

Let's wait for @sindresorhus opinion about...
