### ISSUE TITLE
Clarifying the purpose of correctAutomatically

### ISSUE THREAD

**Issue by eengoron** [sindresorhus/electron-context-menu#101]
Hey @sindresorhus -- 

First, I just wanted to say thank you for getting spellcheck merged. This is awesome! 

I'm currently updating my application to use native spellcheck, and I had a quick question about the `correctAutomatically` menuitem. 

How is this item supposed to be used? From https://github.com/sindresorhus/electron-context-menu/blob/1286195e005d3b7d59371d684d8c619d9f39a9f7/index.js#L44-L50 it looks like it [mimics the functionality of clicking on the first spelling suggestion item](https://github.com/sindresorhus/electron-context-menu/blob/1286195e005d3b7d59371d684d8c619d9f39a9f7/index.js#L211) which shows up earlier in the context menu order. 

Is there something I'm missing here? If that is the case, would you be open to a PR to hide it behind a `showCorrectAutomatically` flag? 

Thanks again!

**Comment by sindresorhus** [comment]
You're right. It's not very useful. It should not have been added. I missed how it worked when reviewing the PR. The PR that added the spellchecking was pretty sloppy, so I'm not surprised I missed something.

See: https://github.com/sindresorhus/electron-context-menu/releases/tag/v2.0.0

**Comment by eengoron** [comment]
Thanks @sindresorhus!

**Comment by jbhaywood** [comment]
I was curious about that too when I saw it in the README. Mention of it should probably be removed.

_To get spellchecking, “Correct Automatically”, and “Learn Spelling” in the menu, make sure you have not disabled the spellcheck option (it's true by default) in BrowserWindow._
