### ISSUE TITLE
Is there a way to get the input element when clicked?

### ISSUE THREAD

**Issue by amanharwara** [sindresorhus/electron-context-menu#102]
I want to add certain text into a textbox when the user clicks an item in the context menu. For this, it will be necessary to get the textbox element itself when clicked. Is this possible somehow?

**Comment by sindresorhus** [comment]
The menu options (`menu`/`append`/`prepend`) include the `params` object, which contain `x`/`y` positions, which you could pass to `document.elementFromPoint(x, y);`, to get the element.

**Comment by amanharwara** [comment]
Thanks, that works.

**Comment by amanharwara** [comment]
Turns out it doesn't quite work as intended. The `x` and `y` co-ordinates seem to be where the user clicked the menu item, not the element.

**Comment by sindresorhus** [comment]
Then I don't know. You could try opening a feature request on https://github.com/electron/electron to include the DOM element in the `params` object.

**Comment by amanharwara** [comment]
Alright, I'll do that. Thanks for replying. I'll close the issue.

**Comment by IProudNoob** [comment]
It's not work

**Comment by drschwabe** [comment]
@amanharwara You can accomplish this by capturing the click in the render process and using `ipcRenderer.send` to send the context you need, which you can then use apart of your logic in electron-context-menu function.   

For example, in your render process (browser context):  

```js
const ipcRenderer = window.require('electron').ipcRenderer

$(document).mousedown(event => {
  if( event.which == 3) {
   //this is a right click, so electron-context-menu will be appearing... 
   let textBoxClicked = $(event.target).closest('.MY-TEXTBOX') 
   if(textBoxClicked.length) ipcRenderer.send('right-click/' + $(textBoxClicked).attr('id') ) 
  }
})
```

then in your electron process: 

```js
let clickedElemId = null
electron.ipcMain.on('right-click', (event, elemId) => {
  if(!elemId) {
    clickedElemId = null
    return
  } 
  clickedElemId = docId
})

require('electron-context-menu')({
    showSearchWithGoogle : false,
    append: (defaultActions, params, browserWindow) => [
    {
      label: 'Add Text to Box',
      // Only show it when right-clicking a box: 
      visible: _.isString(clickedElemId), 
      click () {
        mainWindow.webContents.send('add-text-to-box')
      }
    }]
  })
}

```
