### ISSUE TITLE
 the context menu when no dictionary suggestions

### ISSUE THREAD

**Issue by maziyank** [sindresorhus/electron-context-menu#103]
Hi, 
I just installed version 2.0.0
my problem occurred when a correct text was selected (not misspelled), the context menu in my application goes like this

![electroncontextmenuspell](https://user-images.githubusercontent.com/3317904/80915901-6995a800-8d7f-11ea-82b1-034722b9c204.png)

Probably when there is no dictionary suggestion, the separator between dictionary suggestion should not exist

**Comment by sindresorhus** [comment]
// @nautatva

**Comment by nautatva** [comment]
Check if this commit solves the issue.

**Comment by maziyank** [comment]
thanks @nautatva

**Comment by maziyank** [comment]
when there were no suggestions I print the menu item in the console. It goes like this.

`  [... {
    id: 'learnSpelling',
    label: 'Learn Spelling',
    visible: '',
    click: [Function: click]
  },{
    id: 'dictionarySuggestions',
    label: 'No Guesses Found',
    visible: '',
    enabled: false
  }..],
`

I think this can be solved by fixing **removeUnusedMenuItems** func.
`return menuTemplate
		.filter(menuItem => menuItem !== undefined && menuItem !== false && menuItem.visible !== false && menuItem.visible !== "")
`
