### ISSUE TITLE
Menu no longer appears when right clicking images after upgrading from 0.16.0

### ISSUE THREAD

**Issue by Slapbox** [sindresorhus/electron-context-menu#105]
Hey @sindresorhus, great work! I was surprised when I upgraded to `1.0.0` and everything seemed to work as intended without any changes. As a result I'm not entirely sure where this issue got introduced since we're on `2.0.0` now. I just noticed this yesterday.

I'm not sure if it's related to our implementation. We're building a custom menu like:

```js
const getDefaultMenu = (
  params,
  { selection, menuActions, target }
) => {
  // ... other actions
  menuActions.saveImageAs(),
  menuActions.copyImage(),
}
```

Every other option works as intended, but right clicking images shows no menu at all, including no `Inspect element` option, which makes me think that perhaps it's not related to our constructing a custom menu?

Any thoughts? We could always revert to `0.16.0` but that would be a shame since it's _so_ close to 100% working.

Thanks again for sharing your great work!

**Comment by sindresorhus** [comment]
// @nautatva @loopmode

**Comment by nautatva** [comment]
This works perfectly fine in `fixture.js`:
```
const getDefaultMenu = (
  params,
  { selection, menuActions, target }
) => [
  // ... other actions
  menuActions.saveImageAs(),
	menuActions.copyImage(),
]

contextMenu({getDefaultMenu, showSaveImageAs: true,});
```

Did I get you correctly? Is this the way you wanted to implement the code?

**Comment by Slapbox** [comment]
@nautatva that's more or less what we're doing, but we're building our own menus. The parent function that calls `getDefaultMenu` looks something like this:

```js

export default function createContextMenu({ attachTo }) {
  contextMenu({
    window: attachTo,
    menu: (menuActions, params, win) => {
      const target = webContents.getFocusedWebContents();
      const isLink = !!params.linkURL;

      const menu = isLink
        ? getLinkMenu(params)
        : getDefaultMenu(params, {
            selection,
            menuActions,
            target,
          });
      });
}
```

In this case we're not passing `showSaveImageAs: true` because we're passing our own `menu` entirely.

This bit from the docs is still correct, right?

> The following options are ignored when `menu` is used:
   > - `showLookUpSelection`
   > - `showCopyImage`
   > - `showCopyImageAddress`
   > - `showSaveImageAs`
   > - `showInspectElement`
   > - `showServices`
   > - `showSearchWithGoogle`

**Comment by Slapbox** [comment]
Not an electron-context-menu issue - my apologies. I still have no idea what it could be, but I've ruled this. Apologies I wasn't able to sooner, changing dependencies for our monorepo is, unfortunately, a nearly half hour task.
