### ISSUE TITLE
showSaveImage option is ignored

### ISSUE THREAD

**Issue by rer145** [sindresorhus/electron-context-menu#108]
When setting showSaveImage to false, the context menu still shows that option no matter what. 

`contextMenu({
	showCopyImage: true,
	showCopyImageAddress: false,
	showSaveImage: false,
	showSaveImageAs: true
});`

This results in "Save Image", "Save Image As", and "Copy Image" all appearing in the menu. In this instance, I am only looking for "Save Image As" and "Copy Image", since "Save Image" in itself does nothing.

**Comment by sindresorhus** [comment]
I just tried and worked for me. Sounds like you're on an old version. This was added a while ago: https://github.com/sindresorhus/electron-context-menu/commit/2f1bae0f773330264d31c77e6616f9f720d03779
