### ISSUE TITLE
Add submenu support

### ISSUE THREAD

**Issue by macdevign** [sindresorhus/electron-context-menu#114]
Hi, 
is it possible to have submenu ?
Can this be added if it yet to be supported ?

**Comment by sindresorhus** [comment]
You can add menu items yourself by either prepending or appending. A menu item can have a submenu. This is all in the docs.

**Comment by ithil** [comment]
For anyone still searching: it's [in the Electron docs](https://www.electronjs.org/docs/latest/api/menu-item) not in the `electron-context-menu` docs. And it would look like this:

``` javascript
contextMenu({
  prepend: (defaultActions, parameters, browserWindow) => [
        {
          label: 'My Menu Item with Children',
          submenu: [
            {
              label: 'Child Item 1',
            },
            {
              label: 'Child Item 2',
            },
          ],
        },
      ]
})
```
Note that `submenu` is an array of `MenuItem`s.
