### ISSUE TITLE
Missing Select All?

### ISSUE THREAD

**Issue by greggman** [sindresorhus/electron-context-menu#118]
If I right click in the browser I get a select all option but I don't here. Should that be a standard feature like copy and paste are?

![nhiaV3s0NM](https://user-images.githubusercontent.com/234804/93068066-f863eb00-f6b6-11ea-8fc2-8295b6c87f55.png)

**Comment by sindresorhus** [comment]
I target the Safari context menu, not the Chrome one:

<img width="268" alt="Screen Shot 2020-09-19 at 00 26 51" src="https://user-images.githubusercontent.com/170270/93650456-d2b84800-fa0e-11ea-8146-e46a5280371f.png">

I don't find "select all" very useful as you can just tripple-click in those rare situations you need it.

**Comment by greggman** [comment]
There are other platforms than just Mac. Windows doesn't do triple click to select all so it's much more important there to support it.

**Comment by sindresorhus** [comment]
Do many of the built-in Windows apps have "Select All" (WordPad, Notepad, etc)?

**Comment by greggman** [comment]
Notepad yes

![notepad_D8Ff7nbCEJ](https://user-images.githubusercontent.com/234804/93691802-84499d00-fb25-11ea-9b22-001726168150.png)


Wordpad No

![wordpad_zPMN21aXou](https://user-images.githubusercontent.com/234804/93691806-87dd2400-fb25-11ea-90c3-143d31a23ce7.png)


Edge Yes

![ApplicationFrameHost_xv6kPKfYfU](https://user-images.githubusercontent.com/234804/93691808-8c094180-fb25-11ea-9a83-f486f2c62974.png)

**Comment by sindresorhus** [comment]
Hehe. Windows and it's fantastic consistency. I guess we can add it to Windows only then.

**Comment by Yash-Singh1** [comment]
Works in Ubuntu also

**Comment by coreybruce** [comment]
At least in Linux it's consistent ;)
