### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by jjeff** [sindresorhus/electron-context-menu#119]
I am new to Electron, so I apologize if this is a noob question.

The first line of the `readme.md` says 

> "Electron doesn't have a built-in context menu. You're supposed to handle that yourself. But it's both tedious and hard to get right."

Yet, it appears that Electron does have built-in context menu support through [`menu.popup()`](https://www.electronjs.org/docs/api/menu#menupopupoptions). Is readme file outdated, or am I misunderstanding what `menu.popup()` does? If I am misunderstanding, perhaps you could add a line to the `readme.md` file explaining what `electron-context-menu` offers over `menu.popup()`.

Again, apologies for my noob-ish confusion. But maybe this question/issue will help others not to be confused like me. 🙂

**Comment by sindresorhus** [comment]
That's just an API to create a menu. It's up to you to fill that menu. That's what `electron-context-menu` does.
