### ISSUE TITLE
Context menu in BrowserView (right click)

### ISSUE THREAD

**Issue by josephernest** [sindresorhus/electron-context-menu#124]
Congrats for your project @sindresorhus, which looks very useful!

Just to be sure, you say:

> Electron doesn't have a built-in context menu. You're supposed to handle that yourself.

Is that true also for `BrowserView` elements? 

I mean when we have a "browser inside an Electron app", do we also have to use `electron-context-menu` as well?

Or can we ask `BrowserView` to use the default Chromium context menu:

![](https://i.stack.imgur.com/VxeSp.png)

?

**Comment by sindresorhus** [comment]
Yes, Electron doesn't have the Chrome context menu, even in `BrowserView`.

**Comment by josephernest** [comment]
Thank you @sindresorhus for your answer.

Do you have an example code / template of menu using your `electron-context-menu`, as close as possible as the original Chrome context menu? (I see there are many options, but you probably have such an example).

**Comment by sindresorhus** [comment]
The defaults should be pretty close to Chrome, except missing some things that are not important. I modeled the default menu on Safari as Chrome generally is not good at UX.

**Comment by josephernest** [comment]
It seems the context menu is not triggered when the right-click happens in a `BrowserView`. What specific code should be added in the case of a `BrowserView`?

Reproducible test:

main.js:
```
const {app, BrowserWindow, BrowserView} = require('electron');
const contextMenu = require('electron-context-menu');

contextMenu({prepend: (defaultActions, params, browserWindow) => [{ label: 'Test', visible: true }]});

app.on('ready', () => {
    browserWindow = new BrowserWindow();
    browserWindow.webContents.loadURL('file://' + __dirname + '/index.html');

    bv = new BrowserView();
    bv.setBounds({ x: 0, y: 100, width: 800, height: 400}); 
    bv.webContents.loadURL('https://example.com');
    browserWindow.setBrowserView(bv);
});
```

index.html
```
<html>
<head>
</head>
<body>
Hello world, right click on me! Context menu works!
</body>
</html>
```

Right-clicking on `Hello world, right click on me!` works, but not if you right-click on Example.com:

![image](https://user-images.githubusercontent.com/6168083/102235846-0feb8380-3ef3-11eb-87f7-473609ef607a.png)

**Comment by josephernest** [comment]
Are you able to reproduce the problem @sindresorhus?
Can we reopen the issue #124 so that if someone has an idea he can contribute too?
Thank you

**Comment by sindresorhus** [comment]
Ah, I confused this with the webview tag. `BrowserView` is indeed not yet supported here. https://github.com/sindresorhus/electron-context-menu/issues/125
