### ISSUE TITLE
Spell check suggestions only work for primary language

### ISSUE THREAD

**Issue by benjaminfrombe** [sindresorhus/electron-context-menu#128]
Hi,

in OSX, you can select several preferred languages which are autodetected through a native OSX api if I'm correct.

The language is detected automatically (so that works), as spelling errors are underlined in red. Unfortunately only suggestions in the primary language are given. So if my secondary language is Dutch, and I type an error, this is underlined but only english suggestions are being made in the context menu. 

Can this be fixed ?

**Comment by sindresorhus** [comment]
You need to report this over at https://github.com/electron/electron. This package just uses the Electron APIs for spellchecking.
