### ISSUE TITLE
Add "Save Image As..." menu item

### ISSUE THREAD

**Issue by fritx** [sindresorhus/electron-context-menu#13]
Docs: https://github.com/sindresorhus/electron-dl#saveas
Now I have to fork the whole library to give the tweak :/

``` js
download(win, props.srcURL, { saveAs });
```

**Comment by Razzeee** [comment]
Electron-dl just needs to be bumped to the newest version in the `package.json`. Would be really nice if that could be in the next release.

**Comment by sindresorhus** [comment]
It should instead be a separate menu item called "Save Image As...". https://github.com/sindresorhus/electron-context-menu/issues/14 would be a good fit for such item.

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/electron-context-menu/commit/eaad64400c268d6fb746f17397569f56778a877e.
