### ISSUE TITLE
Remove remote module?

### ISSUE THREAD

**Issue by Slapbox** [sindresorhus/electron-context-menu#133]
@sindresorhus do you have any tips on how to approach this task for this project?

I'm finding it a bit difficult to reason about this package. Part of my difficulty comes from this bit: https://github.com/sindresorhus/electron-context-menu/blob/main/index.js#L7

Is there a use case where relying on `webContents.getFocusedWebContents()` would fail?

What parts of this package, if any, actually need to run in the renderer?

**Comment by sindresorhus** [comment]
> Is there a use case where relying on webContents.getFocusedWebContents() would fail?

This package works directly in both the main and renderer process. `BrowserWindow` is only directly available in the main process.

**Comment by Slapbox** [comment]
@sindresorhus can you give any other tips for this task?

I'm looking into doing it but there's a lot going on here in single file used across both process types. If I'd been involved in the initial code I'm sure it would make fine sense, but it's rather difficult to grok the full workflow coming in fresh. It probably doesn't help that we've leaned on your excellent work as a crutch for so long! [Heck, even most resources discussing how to implement a context menu just suggest starting with your work.](https://ourcodeworld.com/articles/read/874/how-to-implement-a-native-context-menu-with-inspect-element-in-electron-framework)

[Like this bit for example](https://github.com/sindresorhus/electron-context-menu/blob/621c29a8a133925ac25529e4bea2a738394e8609/index.js#L391) It seems like it only needs to be called once, and only in the `main` process - but it's written to accommodate the `renderer` too. I assume in this case it's not necessary to accommodate the `renderer` and set up an IPC channel for this - because it's only needed in `main`. Would you agree?

Are there any other high level tips you can give me for making sense of the code?

**Comment by sindresorhus** [comment]
I think it will be too complicated to make this package *just work* in both the main and renderer process. I suggest removing support for the renderer process. A user can set up their own IPC for this if needed.

**Comment by dusansimic** [comment]
I'd like to work on this issue. Should we expect users to know what they're doing or should there be some kind of check weather it's being required in the main or the renderer process?

**Comment by sindresorhus** [comment]
We should throw a useful error if it's required in the renderer process.
