### ISSUE TITLE
Make it more easily extendable

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/electron-context-menu#14]
The `append` and `prepend` options solve most use-cases, but there are still some people that want 100% control. Would be nice to expose a way to build the menu with ready made components, like lego. I'm thinking:

``` js
require('electron-context-menu')({
    menu: x => [
        x.COPY,
        {
            title: 'foo'
        },
        x.INSPECT
    ]
});
```

Where `x.COPY` is a `Symbol` that includes the built-in cut/copy/paste menus. That way it would be easy to add many more built-in menu types users could pick from.

**Comment by callodacity** [comment]
+1 for this definitely.

I find myself wanting to all `SelectAll` to the default `cut` `copy` `paste` commands.

I think your above syntax is a good approach, something like:

```js
require('electron-context-menu')({
    prepend: params => [],
    append: params => [],
    menu: defaults => [
        defaults.COPY,
        <custom menu item>,
        defaults.INSPECT
    ]
});
```

and it the `menu` item isn't set, obviously default back to normal.

**Comment by sindresorhus** [comment]
> I find myself wanting to all SelectAll to the default cut copy paste commands.

@callodacity Keep in mind that "Select all" is never in the context menu on macOS or Linux, but rather in the top menubar "Edit" menu. Only on Windows it's in the context menu. I should probably create a built-in for that. The reason this module is opinionated is to ensure users implement items correctly, like this case.

**Comment by callodacity** [comment]
@sindresorhus "Select All" is in the context menu on macOS when right-clicking inside any textarea or input (try it in the write comments section or the main text input on [google](www.google.com)). But I definitely agree that keeping it standard is always best. However, think it's important that this module is extendable / customisable too.

**Comment by sindresorhus** [comment]
@callodacity That's just Chrome being non-native as usual. Try Safari or any of the builtin macOS apps.

-

> However, think it's important that this module is extendable / customisable too.

Yup, that's the plan.

**Comment by callodacity** [comment]
@sindresorhus Good point, I missed that. 
Keep up the good work then mate 👍

**Comment by arnellebalane** [comment]
Hi @sindresorhus ! I found myself needing this feature for an Electron app I'm building, so I would like to give it a shot implementing this one. I will base it on your idea above. :smiley:

**Comment by jarivo** [comment]
@sindresorhus 

As I mentioned in #43, I started working on this issue.
In the current implementation, some options are displayed depending on the context (image, link).
How would we let the user change them? Just like a regular item in the menu property and let the context menu handle whether or not they should be displayed? We could also choose to create a new property to the items for images, links...

**Comment by sindresorhus** [comment]
> but new features could take advantage of faster speeds

The item itself decides whether or not it should be visible based on the context.

**Comment by JoniVR** [comment]
Is anyone still working on this? 
I think this would be required for https://github.com/sindresorhus/caprine/issues/248.

I try implementing it if not? Is there already a consensus on how it would be best solved?

**Comment by sindresorhus** [comment]
@JoniVR https://github.com/sindresorhus/electron-context-menu/pull/44 You could help  out by reviewing that one (and maybe also help fixing the merge conflicts if you have the time).

**Comment by JoniVR** [comment]
@sindresorhus Sure 👍🏻

**Comment by JoniVR** [comment]
@sindresorhus 
Quick question, how would one help fixing the merge conflicts?
Just submit a PR on his fork I'm guessing since I don't have write permissions?
