### ISSUE TITLE
Unclear documentation: please add sample code for enabling hidden built-in options

### ISSUE THREAD

**Issue by Jaifroid** [sindresorhus/electron-context-menu#145]
Thank you very much for this module! It's very useful. The only issue is that the documentation is opaque. More mainstream examples are needed. For example, many devs will want to add a quick context menu using options that are pre-defined in electron-context-menu but which are turned off by default.

Suggestion: Could you please add a copy-and-paste example for rushed developers who want to get this working as fast as possible? The "Rainbow" example you give is not very mainstream. For example, please add sample code for enabling image "Save As...", since this is hidden by default. Or maybe just give the full example below, which devs can then customize. It took me a long time to find the sample template below, which is working fine in my app now (I found this out from the closed issue #135):

```
const contextMenu = require('electron-context-menu');

contextMenu({
	labels: {
		cut: 'Cut',
		copy: 'Copy',
		paste: 'Paste',
		save: 'Save Image',
		saveImageAs: 'Save Image As…',
		copyLink: 'Copy Link',
		saveLinkAs: 'Save Link As…',
		inspect: 'Inspect Element'
	},
	prepend: () => { },
	append: () => { },
	showCopyImageAddress: true,
	showSaveImageAs: true,
	showInspectElement: true,
	showSaveLinkAs: true,
	cut: true,
	copy: true,
	paste: true,
	save: true,
	saveImageAs: true,
	copyLink: true,
	saveLinkAs: true,
	inspect: true
});

```

**Comment by sindresorhus** [comment]
While I agree the initial example could be simpler, I think the docs are quite clear already. But yes, I can add another example.

**Comment by Jaifroid** [comment]
Thank you. I'm sure future devs will be grateful too. Not all of us come from a strong Node or Electron background, so things that may seem perfectly clear simply from the documentation of the API can take a long time to work out.
