### ISSUE TITLE
Electron 15: Module '"electron"' has no exported member 'WebviewTag'

### ISSUE THREAD

**Issue by ThomasOrlita** [sindresorhus/electron-context-menu#148]
After updating to Electron 15, TypeScript fails with:

    node_modules/electron-context-menu/index.d.ts:4:2 - error TS2305: Module '"electron"' has no exported member 'WebviewTag'.

https://github.com/sindresorhus/electron-context-menu/blob/88cc8071ea72fc1f81ae22be1c9c35a6587ecadb/index.d.ts#L4

**Comment by jcv8000** [comment]
I'm having the same problem, for now you can get around it by requiring it like this until it gets fixed:
```js
// eslint-disable-next-line @typescript-eslint/no-var-requires
const contextMenu = require("electron-context-menu");
```

**Comment by HemalR** [comment]
> I'm having the same problem, for now you can get around it by requiring it like this until it gets fixed:
> 
> ```js
> // eslint-disable-next-line @typescript-eslint/no-var-requires
> const contextMenu = require("electron-context-menu");
> ```

This works 👍 However (unless I am missing a step), it disables the typings, is that right?

Another option I found while searching for a solution was to modify tsconfig:

```
"compilerOptions": {
  "skipLibCheck": true
}
```
This seems to also work, without the side effect of disabling typings. But is there another downside that I am missing here? Someone more clued in with Typescript can hopefully chip in if so.

**Comment by jcv8000** [comment]
> Another option I found while searching for a solution was to modify tsconfig:
> 
> ```
> "compilerOptions": {
>   "skipLibCheck": true
> }
> ```
> 
> This seems to also work, without the side effect of disabling typings. But is there another downside that I am missing here? Someone more clued in with Typescript can hopefully chip in if so.

I ended up doing this too because so many of the libraries I was using have this same issue
