### ISSUE TITLE
How should it be used with Electron's <webview>?

### ISSUE THREAD

**Issue by eladams** [sindresorhus/electron-context-menu#17]

**Comment by sindresorhus** [comment]
You pass a reference to the `<webview>` to the `window` option. Webview was just added a week ago: https://github.com/sindresorhus/electron-context-menu/pull/15 ;)

**Comment by eyalap** [comment]
@sindresorhus Can you post an example of passing the reference please.
The docs are very minimal with actual usage examples.
Also, The webview I have in my app is created conditionally and isn't always there

**Comment by Polunom** [comment]
@eyalap 
Say you have a webview like
```
<webview id="webview" src="http://google.com">
```

You can initialize the context menu using:
```
const webview = document.querySelector("#webview");
contextMenu({
  window: webview
});
```

**Comment by eyalap** [comment]
Thanks @Polunom , I didn't want to query the DOM from the main process every time I render a new webview.
In any case I used the workaround I was given in https://github.com/sindresorhus/electron-context-menu/issues/65
