### ISSUE TITLE
Cannot paste copied links on Windows (10)

### ISSUE THREAD

**Issue by jnugh** [sindresorhus/electron-context-menu#18]
Hi there,

when I copy a link on WIndows a bookmark is being written to the clipboard:
```javascript
electron.clipboard.writeBookmark(props.linkText, props.linkURL);
```
I'm not able to paste this bookmark in most applications including the electron app I copied it from. The only app I found which allows pasting these bookmarks is actually Chrome.

I could create a PR to make this configurable, but wasn't sure what the actual advantage of the bookmark API is and if there might be another way to fix this.

**Comment by sindresorhus** [comment]
Sounds like an Electron bug. On macOS, at least, it gracefully falls back to plain text when the link type is not supported for pasting. Could you open an Electron issue about this? Happy to accept a PR to use the plain text pasting on Windows for now.

**Comment by jnugh** [comment]
Maybe more like a Windows bug. As I said, the bookmark cannot be pasted into most applications like:
* Skype
* Notepad
* Visual Studio
* Mail
Looking at the apps I tested, it only worked in Chrome.

> Happy to accept a PR to use the plain text pasting on Windows for now.

Maybe someone uses the Bookmark Clipboard manually in the app and relies on Copy link to create a bookmark - I would rather add an option switch.

**Comment by sindresorhus** [comment]
> Maybe more like a Windows bug.

I still think it's worth opening an Electron issue. There might be something they can do to work around, and if no other option, at least document more clearly its limitation.

> Maybe someone uses the Bookmark Clipboard manually in the app and relies on Copy link to create a bookmark - I would rather add an option switch.

I doubt it. It was never documented to copy a bookmark I only added it as a nice implementation detail bonus, as I thought it worked the same on Windows as on macOS. I don't like options when they're not really necessary.
