### ISSUE TITLE
Add menu item for copying link of an image

### ISSUE THREAD

**Issue by egoist** [sindresorhus/electron-context-menu#20]

**Comment by sindresorhus** [comment]
Sure. PR welcome. Should be an option that is false by default.

**Comment by daveseco7** [comment]
I can give this a try if it is ok with everyone.

**Comment by sindresorhus** [comment]
@daveseco7 Make sure you see the review comments in https://github.com/sindresorhus/electron-context-menu/pull/21 and https://github.com/sindresorhus/electron-context-menu/pull/39.
