### ISSUE TITLE
Allowing i18n of the labels. 

### ISSUE THREAD

**Issue by coupej** [sindresorhus/electron-context-menu#22]
What would be the recommended way of translating/overwriting the default labels? Maybe it would be interesting to take that into account when implementing an implementation for issue #14?

**Comment by sindresorhus** [comment]
How about an option named `labels` that accepts an object of labels to override?

```js
require('electron-context-menu')({
	labels: {
		cut: 'Cut',
		copy: 'Copy',
		inspect: 'Inspect'
	}
});
```

Doesn't have to wait for #14.
