### ISSUE TITLE
Error raised when inspecting element while window is not in focus

### ISSUE THREAD

**Issue by jacwright** [sindresorhus/electron-context-menu#26]
Repro:
* Open devtools, pop them out if in-window
* Right-click main window and choose Inspect Element while the devtools window is focused

Actual:
Error popup
> Uncaught Exception:
> TypeError: Cannot read property 'webContents' of null

Desired:
Element clicked on should be inspected

It seems that the window argument passed to the context menu click callback is the focused window (which is null since devtools is focused), not the clicked window. This ought to be fixed upstream in electron. However, until that happens, you should null-check `win` here:
https://github.com/sindresorhus/electron-context-menu/blob/6705425a1669f9290b2873de8b8e1963c9e50d54/index.js#L93

Logged a bug upstream here https://github.com/electron/electron/issues/8209

**Comment by djalmaaraujo** [comment]
@sindresorhus This is working on 0.9.1 release. Please, double test and close. I was having the same issue and latest release fixes.

**Comment by sindresorhus** [comment]
Confirmed fixed.
