### ISSUE TITLE
I can only see Inspect Element option

### ISSUE THREAD

**Issue by alisiddiq** [sindresorhus/electron-context-menu#27]
I have tried using this at the start of my main.js:

require('electron-context-menu')({
    prepend: (params, browserWindow) => [{}]
});

I can only get the inspect Element menu and cannot figure out what extra things I need to do to add more options like Reload page to the context menu. Please help.

**Comment by sindresorhus** [comment]
It's documented right in the `Usage` section how to add a custom element: https://github.com/sindresorhus/electron-context-menu#usage
