### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by zackshapiro** [sindresorhus/electron-context-menu#29]
After running `npm install --save electron-context-menu` and adding 

```
require('electron-context-menu')({
    prepend: [{}],
    showInspectElement: true,
});
```

I've tried a variety of configurations, nothing seems to add Inspect Element to my rightclick menu, which I don't have. I tried looking into the source and have come up empty so I'd love advice on how to get this working.

Thanks!

**Comment by sindresorhus** [comment]
Maybe related to https://github.com/sindresorhus/electron-is-dev/issues/4?

**Comment by benjaminsuch** [comment]
Try changing `prepend: [{}]` to `prepend: (params, browserWindow) => []`

**Comment by zackshapiro** [comment]
@benjaminsuch no luck, unfortunately

**Comment by sindresorhus** [comment]
> Maybe related to sindresorhus/electron-is-dev#4?

@zackshapiro Regarding ⬆️, do you have `electron` in your projects filepath?

**Comment by zackshapiro** [comment]
I do not, no

**Comment by sindresorhus** [comment]
Try doing some debugging. Last thing I could think of, try removing this line: https://github.com/sindresorhus/electron-context-menu/blob/6705425a1669f9290b2873de8b8e1963c9e50d54/index.js#L115

**Comment by zackshapiro** [comment]
I've been trying this work weeks, I've done plenty of debugging which is why I posted the issue. Did my requisite research before I posted an issue 

Best,
Zack




On Mon, Feb 27, 2017 at 1:24 AM -0500, "Sindre Sorhus" <notifications@github.com> wrote:












Try doing some debugging. Last thing I could think of, try removing this line: https://github.com/sindresorhus/electron-context-menu/blob/6705425a1669f9290b2873de8b8e1963c9e50d54/index.js#L115

**Comment by zackshapiro** [comment]
I'd love help getting this work. It's so simple, I can't imagine what I'm doing wrong. Thanks
