### ISSUE TITLE
Visible does not work

### ISSUE THREAD

**Issue by adi518** [sindresorhus/electron-context-menu#31]
The default example doesn't work as expected. I can click wherever and the menu would show. It seems it should trigger only if an `img` tag was clicked, correct?

Seems to work great otherwise and much easier to integrate compare to other offerings.

**Comment by sindresorhus** [comment]
Not entirely clear what you're asking. The menu triggers whenever there are something to show in the menu, meaning whenever you're in an input box or have marked some text or right-clicking an image.

**Comment by adi518** [comment]
What does this option do? `visible: params.mediaType === 'image'`. It seems I misunderstand it.

**Comment by sindresorhus** [comment]
> What does this option do? visible: params.mediaType === 'image'.

That's already explained in the example: `// only show it when right-clicking images`.

**Comment by adi518** [comment]
Yes, seemed trivial, but I don't think it was working for me. I'll try again.
