### ISSUE TITLE
How to enable webview context menu?

### ISSUE THREAD

**Issue by lhongda** [sindresorhus/electron-context-menu#37]
Hi! I try to use the code follow to enable webview context menu but it not work!
```const electron = require('electron');
const BrowserWindow = electron.BrowserWindow;
const WebView = electron.WebView;
require('electron-context-menu')({
    window: WebView,
    prepend: (params, browserWindow) => [{
        labels: {
            cut: 'Configured Cut',
            copy: 'Configured Copy',
            paste: 'Configured Paste',
            save: 'Configured Save Image',
            copyLink: 'Configured Copy Link',
            inspect: 'Configured Inspect'
        },
        // Only show it when right-clicking images
        visible: params.mediaType === 'image'
    }]
}); 
```
I guess the key is the this statment ```const WebView = electron.WebView;```, I don't know how where to get the WebView Type.
The result is still just work for BrowserWindow!
so, how can I fix the code to enable that? Thanks !

**Comment by lhongda** [comment]
I have already fix it.

**Comment by lhongda** [comment]
Know the problem is how to save canvas when right click, because canvas tag have not url attribute, so how to implement save canvas?

**Comment by sindresorhus** [comment]
Make sure you're using v0.9.0. It added support for webviews. They should now *just work*.

**Comment by lhongda** [comment]
I have solve the problem of show context menu in webview, but I still can't resolve the  problem that how to save canvas tag as image by right click.

**Comment by sindresorhus** [comment]
> but I still can't resolve the problem that how to save canvas tag as image by right click, did you have any idea of it ? Thanks!

That is not relevant to this module. Canvas is not an image. You can create your own menu item for that. The default "Save as Image" menu item is for images only.

**Comment by zhangqiwangwei** [comment]
> 我已经解决了。



> 我已经解决了。


How to solve this problem?

**Comment by robxxxx** [comment]
Can you tell us how did you apply context menu inside webview?

**Comment by KorbsStudio** [comment]
I am still not understanding how to get this to work

**Comment by sergeyd63** [comment]
love those comments

@Anderson-Liu can you tell us how you fixed it?
my context menu doen't work in webview

**Comment by michaelkofron** [comment]
@sergeyd63 Recently struggling with this problem and would like to know as well. With @Anderson-Liu would have mentioned how he got this to work. I've tried to connect a context menu to a webview in every way imaginable and no good results so far ;(

**Comment by sergeyd63** [comment]
@michaelkofron i found a solution and didn't post it here... (i hate it when people do that 🤦‍♀️  )
  
`app.on("web-contents-created", (e, contents) => {
    if (contents.getType() == "webview") {
      // set context menu in webview
      contextMenu({
        window: contents,
      });
    }
  });`

that did the trick for me

**Comment by michaelkofron** [comment]
@sergeyd63 Wow! So simple! I hope others struggling with this problem come across your amazing solution. Thank you!

**Comment by anantgulia** [comment]
Anybody still looking for the solution check @sergeyd63 's answer ^ it's working

**Comment by patarapolw** [comment]
@sergeyd63 It doesn't for me in Electron 11.

```
TypeError: win.addEventListener is not a function
    at module.exports (/home/polv/projects/zhquiz/submodules/e-zhquiz/node_modules/electron-context-menu/index.js:367:8)
    at App.eval (webpack:///./src/background.ts?:32:86)
    at App.emit (events.js:315:20)
    at Object.b._init (electron/js2c/browser_init.js:157:11741)
    at Object.create (electron/js2c/browser_init.js:157:12444)
    at electron/js2c/browser_init.js:177:2680
    at electron/js2c/browser_init.js:177:3904
    at electron/js2c/browser_init.js:177:2217
    at electron/js2c/browser_init.js:189:579
    at Object.<anonymous> (electron/js2c/browser_init.js:157:9339)
```

**Comment by sergeyd63** [comment]
@patarapolw that's a separate issue, i opened another one for that:

[https://github.com/sindresorhus/electron-context-menu/issues/123](url)

**Comment by arx-001** [comment]
How it will work in web view
and main window Works only in window with this code I
t doesn't work in Web View...
Edit this code to make the context menu work

const { app, BrowserWindow} = require('electron');
const contextMenu = require('electron-context-menu');

contextMenu({
	
	labels: {
		cut: 'Cut',
		copy: 'Copy',
		paste: 'Paste',
		save: 'Save Image',
		saveImageAs: 'Save Image As…',
		copyLink: 'Copy Link',
		saveLinkAs: 'Save Link As…',
		inspect: 'Inspect Element'
	},
	prepend: () => [
		{
			label: 'Arxstd',
		},
		{
			label: 'back',
		},
		{
			label: 'Forward',
		},
		{
			label: 'Reload',
		},
		{
			type: 'separator'
		},
		{
			type: 'separator'
		},
		{
			type: 'separator'
		},
		{
			type: 'separator'
		}
	],
	append: () => { },
	showCopyImageAddress: true,
	showSaveImageAs: true,
	showInspectElement: true,
	showSaveLinkAs: true,
	cut: true,
	copy: true,
	paste: true,
	save: true,
	saveImageAs: true,
	copyLink: true,
	saveLinkAs: true,
	inspect: true
});



let mainWindow;
(async () => {
	await app.whenReady();

	mainWindow = new BrowserWindow({		
		webPreferences: {
			spellcheck: true,
			webviewTag: true,
		}
	});
	mainWindow.loadFile('index.html')
})();


const dispose = contextMenu();

dispose();

**Comment by DarkSynx** [comment]
https://stackoverflow.com/questions/65728995/how-to-create-a-context-menu-in-a-webview-in-electron
```

var menu = new Menu();

//Basic Menu For Testing
menu.append(new MenuItem({ label: 'MenuItem1', click: function() { console.log("YES"); 
} }));
menu.append(new MenuItem({ type: 'separator' }));
menu.append(new MenuItem({ label: 'MenuItem2', type: 'checkbox', checked: true }));
app.on("web-contents-created", (...[/* event */, webContents]) => {

//Webview is being shown here as a window type
console.log(webContents.getType())
webContents.on("context-menu", (event, click) => {
  event.preventDefault();
  console.log(webContents.getType())
  menu.popup(webContents);
}, false);
});

```

**Comment by DarkSynx** [comment]
```
const template = [
	{
    label: '🛠️',
    submenu: [
      { 
		label: '↻ Refresh',
		 accelerator: 'F5',
		 click: (menuItem, browserWindow, event) => {
		 win.reload();
		 }
	  },
      { label: '👨‍💻 openDevTools',
		 accelerator: process.platform === 'darwin' ? 'Alt+Cmd+I' : 'Ctrl+Shift+I',
		 click: (menuItem, browserWindow, event) => {
		 win.webContents.openDevTools()
		 }
	  },
      { type: 'separator' },
      { label: '🚪 exit',
		role: 'quit',
		accelerator: 'Alt+F4'
	  }
    ]
  }
]
	const menubar = Menu.buildFromTemplate(template)

//Webview is being shown here as a window type
console.log(webContents.getType())
webContents.on("context-menu", (event, click) => {
  event.preventDefault();
  console.log(webContents.getType())
  menubar.popup(webContents);
}, false);
});
```

**Comment by vincentformationopen** [comment]
can we change the design of the context menu for the webview ?

**Comment by arxsheikh** [comment]
You will need to create custom events and manage the functionalities yourself, as there are no built-in APIs available.
