### ISSUE TITLE
showInspectElement: false not disabling "Inspect Element"

### ISSUE THREAD

**Issue by GeekStocks** [sindresorhus/electron-context-menu#38]
readme.md states that showInspectElement is a boolean which should...

> "Force enable or disable the Inspect Element menu item."

The following code does NOT disable the Inspect Element menu item:

> require('electron-context-menu')({
>   prepend: (params, browserWindow) => [{
>     label: "Capital Flux™",
>     showInspectElement: false
>   }]
> });

![inspect-still-on](https://cloud.githubusercontent.com/assets/5877307/25530175/527e1ae4-2bf3-11e7-9da8-25075e94ca33.png)

Environment is Electron on Windows 7.

**Comment by sindresorhus** [comment]
You have the option in the wrong place.

Should be:

```js
require('electron-context-menu')({
	prepend: (params, browserWindow) => [{
		label: "Capital Flux™"
	}],
	showInspectElement: false
});
```

**Comment by GeekStocks** [comment]
AHHHH! Thanks - sorry about that. End of day brain. Nice project, works well.
