### ISSUE TITLE
Alter behaviour of default actions/roles e.g. when copying a link

### ISSUE THREAD

**Issue by jarivo** [sindresorhus/electron-context-menu#43]
Hi,

This issue is related to #14, but I think it is appropriate to discuss it separately.

The specific use case for altering the behaviour of the default roles is found in Caprine.
Currently it is impleted that clicking on links removes the tracking bits from the URL.
This is not the case when using the context-menu (e.g. "Copy Link").
Therefore it would be useful to be able to modify the content of that link without the need to rewrite some of the boilerplate.

Thoughts?

**Comment by sindresorhus** [comment]
I agree with the problem, do you have any suggestions on how we could solve this?

**Comment by jarivo** [comment]
With the solution defined in #14, I think a simple callback won't be possible to add a callback to default actions.

I will try and start implementing #14 (in the coming days) and maybe things will become clearer down the road.

**Comment by sindresorhus** [comment]
@jarivo Sure, it could. We could make `x.COPY` => `x.COPY({transform: url => url.replace()})`, but not sure it's the best solution. Maybe we could have a `hook` function that receives every action and is able to modify it or something.

> I will try and start implementing [#14](https://github.com/sindresorhus/electron-context-menu/issues/14 "Make it more easily extendable") (in the coming days)

🤗

**Comment by jarivo** [comment]
I personally prefer your first suggestion, it is clean and "future-proof" for extra options which might be action-specific. If they want a general hook function they can by adding it as a transform for each of them.

The second suggestion is less work on our side, but I think it would become messy when someone needs to implement custom behaviour for all of them. Sure it is much easier when you want to manipulate all incoming text/urls/strings (e.g. replacing http with https)

So I think both of them have some use cases, but the first one seems less of a hurdle for the end user.
