### ISSUE TITLE
Different items depending the element clicked

### ISSUE THREAD

**Issue by angrykoala** [sindresorhus/electron-context-menu#49]
Is it possible to modify the elements on the menu depending on the element clicked, for example, depending on the class or id?

In my case, I have certain boxes that should display a different context menu that other elements, I tried tinkering with the prepend callback but it doesn't provide any information about the clicked element.

**Comment by sindresorhus** [comment]
You can now (soon) also use the `menu` option to completely customize the menu however you want.

**Comment by sindresorhus** [comment]
> I tried tinkering with the prepend callback but it doesn't provide any information about the clicked element.

That's not correct. The first argument passed to `prepend` is a `params` object with that information. See the first example in the readme.

**Comment by b3u** [comment]
@fabiospampinato how do you get the document from the main process?

**Comment by fabiospampinato** [comment]
@b3u I don't, I run most of the logic in the renderer process. I'm not sure you can actually get the DOM node in the main process as that's probably not serializable I guess.

**Comment by yourfavorite** [comment]
Regarding the example code above, is using x/y coords and filtering by selector the best way to go about determining if a specific element was right clicked on? This feels a little brittle to me but maybe its fine and I'm being overly paranoid?

**Comment by loopmode** [comment]
Here's a Gist of how I did it without this library in one react app: https://gist.github.com/loopmode/f1760d6562d9fa04ff73b64d0fe25651

Basically, I needed different context menus per component, so I made a hook and I pass a reference to the DOM element into the hook. Inside the hook, when handling the context menu event, I check if the event.target is either the DOM element I expect, or a child of the expected element. If it isn't - I bail out.

I hope #93 gets merged soon and I'll be happy to provide a similar hook for it. (Then I can drop the stuff from the gist in the app it comes from and use electron-context-menu there as well)

**Comment by yourfavorite** [comment]
Thanks @loopmode this is great. Regarding the performance comment in I saw in your other gist. Do you think there will be much of a performance hit if you have say 100 elements with unique context menus?

**Comment by loopmode** [comment]
I don't think so - basically it's just a bunch of plain object and event listeners.
The app where I used the approach from the gist uses the menu hook in three places: once in the root (this menu stays always atatched), and then in two list pages you can navigate to. 
On the list pages I've had dozens of rows (not hundreds tho), and each uses the hook. I didn't notice any performance hits so far.
I usually navigate between the two list pages, so some 30-40 menus get registered and unregistered again when navigating back and forth, and everything is snappy.

**Comment by fabiospampinato** [comment]
> Regarding the example code above, is using x/y coords and filtering by selector the best way to go about determining if a specific element was right clicked on? This feels a little brittle to me but maybe its fine and I'm being overly paranoid?

There are pros and cons I think.

Regarding the use of coordinates that's how this thing fundamentally works, listing on the "contextmenu" doesn't really work any differently, you're just letting the browser/os/whatever handle the coordinates for you. There's a bug in my code above though, the x and y coordinates should be scaled by the zoom factor, which is `window.outerWidth / window.innerWidth`.

Regarding using a selector this is indeed somewhat brittle as it introduces a reliance on something that's probably hidden in the codebase, like you could change your target elements and forget to update the selector and things will break, I don't think in practice this is too much of a problem though. On the other hand attaching tens or hundreds of event listers to all those target elements might not be great, and using event delegation would be better for performance.

**Comment by Slapbox** [comment]
I don't even see how it's possible to use the `x/y` coordinates because the `contextmenu` event fires immediately but getting the element at `x/y` would require another round trip IPC from main to renderer and back - but `contextmenu` can't be made to wait while that IPC completes.

**Comment by Slapbox** [comment]
@sindresorhus would you be open to a PR to enable this if it added a slight delay to the menu appearing, and if so, what would be your acceptable threshold in milliseconds? 

I don't think it would be very easy to cleanly implement as an optional feature. I'm also not even sure I'll ever get around to it.

**Comment by sindresorhus** [comment]
@Slapbox I don't think that would work well in practice. The required delay would depend on the machine performance, Electron version, and other factors. The best solution is to just do all the logic in the renderer.

**Comment by Slapbox** [comment]
> The best solution is to just do all the logic in the renderer.

I of course agree, but I don't see how without breaking Electron's security model.
