### ISSUE TITLE
electron-context-menu incompatible with electron 2.0.x?

### ISSUE THREAD

**Issue by TheGoddessInari** [sindresorhus/electron-context-menu#56]
I've tried it a number of times with a electron 2.0.x webview and no context menu appears. 
Works fine with electron 1.8.x.
Totally default, no customization.

**Comment by EddieOne** [comment]
working fine for me in 2.x

**Comment by jfrux** [comment]
Okay then does the Usage instructions work with 2.x?

**Comment by EddieOne** [comment]
The usage example it kind of dumb because it only shows a label when right clicking an image. Here's a better one.

```
require('electron-context-menu')({
  prepend: (params, browserWindow) => [{
    label: 'Home', click(){
      mainWindow.loadURL('https://www.example.com/')
    }
  },
  {
    label: 'Back', click(){
      mainWindow.webContents.goBack()
    }
  }]
});
```
