### ISSUE TITLE
Way to disable the label?

### ISSUE THREAD

**Issue by hguiney** [sindresorhus/electron-context-menu#57]
Right now I don’t have a need for the label. However if I set the `label` property in `prepend` to `null` or `undefined`, it just generates a blank label. Is there a way to disable it so the context menu just says Cut, Copy, Paste, and Inspect Element?

**Comment by sindresorhus** [comment]
I don't understand why you're trying to create an element without a label? What's the purpose?

**Comment by hguiney** [comment]
What do you mean? I just want to add Cut, Copy, Paste, and Inspect Element to my Electron app. If I right/ctrl-click in most native apps, there is no label for that set of actions. For instance in TextEdit it just immediately shows you Cut, Copy, and Paste, followed by two more sections:

![](https://i.imgur.com/JDSYouV.png)

Conversely, I don’t understand why a label would be mandatory for this. The only thing I can think to put there would be “Actions”, but that doesn’t really add any meaningful context. I already know that I am bringing up a list of actions by right/ctrl-clicking.

**Comment by sindresorhus** [comment]
You can use the `visible` property to set whether it should show or not.
