### ISSUE TITLE
Copy link is not working on Linux

### ISSUE THREAD

**Issue by akashnimare** [sindresorhus/electron-context-menu#6]
I am using this module on Linux. 
Read/writeBookmark is not implemented yet on Linux, see [here](https://github.com/electron/electron/commit/f90ef128145600899427ef8c5629fa0cd794232d).
I think it's better to use [this](https://github.com/sindresorhus/electron-context-menu/blob/194c6dc553b4a23ee2df272d827f1e0672f8e739/index.js#L55) version which works fine on all three platforms.

**Comment by sindresorhus** [comment]
Oh, I missed it was not implemented on Linux. Fixed now.

**Comment by akashnimare** [comment]
Thanks. I was about to give a exactly same PR. :smile:
