### ISSUE TITLE
Right click to copy the picture how to do

### ISSUE THREAD

**Issue by iwen-pengh** [sindresorhus/electron-context-menu#63]
Right click to copy the picture how to do

**Comment by sindresorhus** [comment]
I'm not sure what you're asking. Please spend some more effort on your question.

**Comment by iwen-pengh** [comment]
右键复制图片 怎么做？ 懂了吗

**Comment by von7750** [comment]
Right click to copy the picture to clipboard, i guess, like chrome "cpoy image"
