### ISSUE TITLE
doesn't show in webview

### ISSUE THREAD

**Issue by eyalap** [sindresorhus/electron-context-menu#65]
Using the latest version. 
I am able to see the context menu in BrowserWindow however I dynamically render <webview> when needed using a react app and don't see the context menu.
I don't pass anything in the window option so according to the documentation it should be visible in the webview by default but isn't.

If I need to pass webview reference I'd like an example if possible, I don't understand how you expect to pass a reference to the webview which is in the renderer while the context menu is in the main process.
I have an ID for the element but can't access and get results from the DOM from the main process or pass the element itself using IPC since it doesn't work.

Thanks

**Comment by agata** [comment]
I found work around for this issue. Please use 'web-contents-created' event and window option.

```js
const electron = require('electron');
const {app, BrowserWindow, shell}  = electron;
const contextMenu = require('electron-context-menu');
...
app.on('web-contents-created', (e, contents) => {
  if (contents.getType() == 'webview') {
    // open link with external browser in webview
    contents.on('new-window', (e, url) => {
      e.preventDefault()
      shell.openExternal(url)
    })
    // set context menu in webview
    contextMenu({
      prepend: (defaultActions, params, browserWindow) => [{
        label: 'Rainbow',
        visible: params.mediaType === 'image'
      }],
      window: contents
    });
  }
});
```

**Comment by eyalap** [comment]
Thanks @agata this workaround works !
@sindresorhus I'm closing this issue, but I do think it will work much better if it would be supported out of the box instead of a workaround like this.
