### ISSUE TITLE
Add support for macOS Services submenu

### ISSUE THREAD

**Issue by caesar** [sindresorhus/electron-context-menu#72]
Native context menus on macOS have a “Services” submenu to which other apps on the system can add actions.

I think this should be fairly trivial to implement using the `services` [role](https://github.com/electron/electron/blob/master/docs/api/menu-item.md#roles) from Electron's menu API.
I'll give it a go later and submit a PR.

Example from Safari:

<img width="537" alt="Screenshot 2019-05-26 at 20 44 02" src="https://user-images.githubusercontent.com/1566516/58386412-70f0f500-7ff7-11e9-9727-86b3ac8390a6.png">

**Comment by caesar** [comment]
As with #3, I should note that in the PR referenced above I chose to enable this menu item by default on macOS, with an option to disable it, because I think *the default should be as much like the default native menus on each platform as possible*.

However, I suppose that adding a new menu item which is enabled by default is a semver-major change. So either:
- This shouldn't be introduced until the next semver-major release; or
- It should be disabled by default until the next semver-major release; or
- It should be disbaled by default anyway.

Thoughts?

**Comment by sindresorhus** [comment]
> because I think the default should be as much like the default native menus on each platform as possible.

I absolutely agree. We can do a breaking change. It's fine.
