### ISSUE TITLE
Creating a context menu makes webview.findInPage() fail

### ISSUE THREAD

**Issue by madprops** [sindresorhus/electron-context-menu#77]
I'm not sure if I'm doing wrong, but when I add:

```
                contextMenu(
                {
                    window: new_webview,
                    showCopyImageAddress: true,
                    showSaveImageAs: true,
                    showInspectElement: true
                })
```

When creating a webview. The findInPage function doesn't work at all.

I created a testing repo for this https://github.com/madprops/webview-test-for-debugging

**Comment by whitecrownclown** [comment]
@madprops 	

Your webview isn't attached to the dom, as you can see in the console.
<img width="535" alt="Screenshot 2019-06-26 at 01 23 32" src="https://user-images.githubusercontent.com/8309417/60137922-25c23180-97b1-11e9-893c-0f266b59b173.png">

I've forked your repo here for a working sample: 
https://github.com/whitecrownclown/webview-test-for-debugging. 

Also: https://github.com/sindresorhus/electron-context-menu/blob/295e19dbae4b3927f199031c53f7219765d2ed96/index.js#L220
