### ISSUE TITLE
Expose function to create menu template

### ISSUE THREAD

**Issue by jiahaog** [sindresorhus/electron-context-menu#8]
Hi! 

I'm looking to use electron-context-menu, but I would like to add additional menu options to the created template, of [`menuTpl`](https://github.com/sindresorhus/electron-context-menu/blob/master/index.js#L12) and set up a callback for this myself.

Would it be possible to expose a function to create the template to do this, as illustrated in the example below below

``` javascript
// expose template creator in electron-context-menu
import {createContextMenuTemplate} from 'electron-context-menu';

win.webContents.on('context-menu', (e, props) => {
    // new exposed function to create the menu template
    const menuTpl = createContextMenuTemplate(props);

    // add more options
    // menuTpl.push(SOME_MORE_OPTIONS)

    const menu = (electron.Menu || electron.remote.Menu).buildFromTemplate(menuTpl);
    menu.popup(win);
});
```

I'll create a pull request for this if you're open to it!

**Comment by sindresorhus** [comment]
Why not just use the `append` or `prepend` option?

**Comment by jiahaog** [comment]
Sorry for the delay! This is because I would like to append a different item to the context menu every time something is clicked. For example, I want to add a context menu option to open a link in a new window, which will be different depending on the link that is clicked

**Comment by sindresorhus** [comment]
The `append` option expects a function that returns an array of menu items. The function is executed on every right-click, so you can return anything dynamically then. Should solve your needs.

You might also be interested in https://github.com/sindresorhus/electron-context-menu/issues/14.
