### ISSUE TITLE
Multiple invocations, destroy function?

### ISSUE THREAD

**Issue by loopmode** [sindresorhus/electron-context-menu#84]
Hi. 
I intend to use a react hook for creating context menus "on the fly" in the renderer process, for particular DOM elements. 
The current implementation is [here](https://gist.github.com/loopmode/81b71f96bebe22697f8c2ee22fa12cf8) and the usage is something like this:
```jsx
const SomeListItem = (props) => {  
  const ref = React.useRef(null);
  useContextMenu(ref, [{
      label: 'Delete',
      click: () => props.onDelete(props.id)
  }]);
  return (
    <li ref={ref}>...</li>
 );
}
```

The hook effectively calls `contextMenu()` whenever the component is mounted to the DOM. Many components may do this many times.

What I wonder is... Shouldn't I be destryoing something when the components gets unmounted again?

I skimmed the code a bit, but it's still not clear to me whether one can or should destroy menus for cleanup reasons.

(I'm aware of the potential performance issues as explained by @fabiospampinato in [78](https://github.com/sindresorhus/electron-context-menu/issues/78) but I don't care about that that for now.)

**Comment by fabiospampinato** [comment]
> I skimmed the code a bit, but it's still not clear to me whether one can or should destroy menus for cleanup reasons.

It doesn't look like this library is storing menu templates indefinitely, I'm not sure about the Electron side of things but I don't think I've read anything in the docs about menus disposal.

You may want to test this yourself by showing a few hundreds menus or something and see via the devtools if more and more object remain allocated in memory.

**Comment by sindresorhus** [comment]
See https://github.com/sindresorhus/electron-context-menu/issues/82
