### ISSUE TITLE
showInspectElement set to true - showing as disabled in 0.12.0

### ISSUE THREAD

**Issue by jennifer-shehane** [sindresorhus/electron-context-menu#86]
Our applications calls into `electron-context-menu` in order to show 1 `Inspect Element` menu. Simplified it is doing this (coffeescript):

```coffee
contextMenu = require("electron-context-menu")

contextMenu({
  showInspectElement: true
  window: win
})
```

The complete code in our project is here: https://github.com/cypress-io/cypress/blob/renovate/electron-context-menu-0.x/packages/server/lib/gui/windows.coffee#L150

This menu is working in version 0.11.0 of `electron-context-menu`, but showing up as disabled in version 0.12.0. 

### 0.11.0

<img width="180" alt="Screen Shot 2019-10-30 at 4 29 58 PM" src="https://user-images.githubusercontent.com/1271364/67896349-90ee8c80-fb32-11e9-8351-2d082601cdd3.png">

### 0.12.0

<img width="289" alt="Screen Shot 2019-10-30 at 4 04 57 PM" src="https://user-images.githubusercontent.com/1271364/67896311-7c11f900-fb32-11e9-8018-addab723bd94.png">

We waited until now to update because of the breaking change for Electron - we recently updated to use Electron 5.0.10. 

Forgive me if I missed something in the changelog that we were meant to update.

**Comment by sindresorhus** [comment]
Fixed in https://github.com/sindresorhus/electron-context-menu/releases/tag/v0.15.1

**Comment by jennifer-shehane** [comment]
Thanks! This did resolve our issue.
