### ISSUE TITLE
Ignores browserWindow `frame : false` in packaged build

### ISSUE THREAD

**Issue by LDubya** [sindresorhus/electron-context-menu#96]
Hi there,

We have set the browserWindow frame to be 'false' in our app, and use our own custom frame. (Looks sleeker than the default).

We'd like to use your extension, but when the app is built and packaged with `const contextMenu = require('electron-context-menu')`, this extension causes the browserWindow's frame to be present. 

Is there a setting to ensure this extension respects our frame settings?

**Comment by LDubya** [comment]
Looks like it also prevents the creation of a new second browserWindow when a current browserWindow exists

**Comment by sindresorhus** [comment]
This package doesn't modify BrowserWindow in any way. This sounds more like an Electron bug.

**Comment by Slapbox** [comment]
There are definitely not `electron-context-menu` bugs unless it's implementation dependent. Neither of the mentioned issues affect us in a multi-window, frameless application.
