### ISSUE TITLE
Deprecated getWebContents() method

### ISSUE THREAD

**Issue by tidg** [sindresorhus/electron-context-menu#99]
Hi,
In the latest version of Electron v8.0.2, we notice webview.getWebContents()' is deprecated and will be removed. Please use 'remote.webContents.fromId(webview.getWebContentsId())' instead.

Is it possible to update 
`const webContents = win => win.webContents || (win.getWebContents && win.getWebContents());` 
to something like this to prevent this warning from causing a problem on the plugin in the future.
`const webContents = win => win.webContents || electron.remote.webContents.fromId(win.getWebContentsId());`

Thank you!

**Comment by Prinzhorn** [comment]
FYI `remote` will be deprecated as well https://github.com/electron/electron/issues/21408

**Comment by br0nstein** [comment]
Sounds like this library is incompatible with Electron 9 then. Electron 9 removed the getWebContents API that was deprecated in Electron 8. https://www.electronjs.org/blog/electron-9-0

**Comment by iwiedenm** [comment]
This package is now broken on Electron 9.x.x because of this error it seems.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/electron-context-menu/commit/a539dc42277f166e977cbd58fac9e9381770ab8e
